/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.c24.giro.client.api;

import de.c24.giro.client.ApiException;
import de.c24.giro.client.model.Bank;
import de.c24.giro.client.model.SaveBankRequest;
import de.c24.giro.client.model.SimpleBankView;
import de.c24.giro.client.model.SimpleProductView;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AdminBankResourceApi
 */
@Disabled
public class AdminBankResourceApiTest {

    private final AdminBankResourceApi api = new AdminBankResourceApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void appendTest() throws ApiException {
        SaveBankRequest saveBankRequest = null;
        Bank response = api.append(saveBankRequest);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteBankTest() throws ApiException {
        String id = null;
        api.deleteBank(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllBanksTest() throws ApiException {
        List<SimpleBankView> response = api.getAllBanks();
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getByIdTest() throws ApiException {
        String id = null;
        Bank response = api.getById(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getProductsByBankTest() throws ApiException {
        String id = null;
        List<SimpleProductView> response = api.getProductsByBank(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateBankTest() throws ApiException {
        String id = null;
        SaveBankRequest saveBankRequest = null;
        Bank response = api.updateBank(id, saveBankRequest);
        // TODO: test validations
    }

}
