/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.c24.giro.client.api;

import de.c24.giro.client.ApiException;
import de.c24.giro.client.model.Product;
import de.c24.giro.client.model.SaveProductRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AdminProductResourceApi
 */
@Disabled
public class AdminProductResourceApiTest {

    private final AdminProductResourceApi api = new AdminProductResourceApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addProductTest() throws ApiException {
        SaveProductRequest saveProductRequest = null;
        Product response = api.addProduct(saveProductRequest);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteProductTest() throws ApiException {
        String id = null;
        api.deleteProduct(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateProductTest() throws ApiException {
        String id = null;
        SaveProductRequest saveProductRequest = null;
        Product response = api.updateProduct(id, saveProductRequest);
        // TODO: test validations
    }

}
