/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.c24.giro.client.api;

import de.c24.giro.client.ApiException;
import de.c24.giro.client.model.Product;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PublicProductResourceApi
 */
@Disabled
public class PublicProductResourceApiTest {

    private final PublicProductResourceApi api = new PublicProductResourceApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getActiveProductsTest() throws ApiException {
        List<Product> response = api.getActiveProducts();
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getProductByIdTest() throws ApiException {
        String id = null;
        Product response = api.getProductById(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getProductByKey11Test() throws ApiException {
        String key = null;
        Product response = api.getProductByKey11(key);
        // TODO: test validations
    }

}
