/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.c24.giro.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.c24.giro.client.model.GraduatedMaintenanceFeeEntry;
import de.c24.giro.client.model.OpeningFees;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AccountFees
 */
public class AccountFeesTest {
    private final AccountFees model = new AccountFees();

    /**
     * Model tests for AccountFees
     */
    @Test
    public void testAccountFees() {
        // TODO: test AccountFees
    }

    /**
     * Test the property 'fixedMaintenance'
     */
    @Test
    public void fixedMaintenanceTest() {
        // TODO: test fixedMaintenance
    }

    /**
     * Test the property 'graduatedMaintenance'
     */
    @Test
    public void graduatedMaintenanceTest() {
        // TODO: test graduatedMaintenance
    }

    /**
     * Test the property 'permanentlyFree'
     */
    @Test
    public void permanentlyFreeTest() {
        // TODO: test permanentlyFree
    }

    /**
     * Test the property 'overdraftInterest'
     */
    @Test
    public void overdraftInterestTest() {
        // TODO: test overdraftInterest
    }

    /**
     * Test the property 'openingFees'
     */
    @Test
    public void openingFeesTest() {
        // TODO: test openingFees
    }

    /**
     * Test the property 'custodyFeeForCredit'
     */
    @Test
    public void custodyFeeForCreditTest() {
        // TODO: test custodyFeeForCredit
    }

}
