/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.c24.giro.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BankingAppGrades
 */
public class BankingAppGradesTest {
    private final BankingAppGrades model = new BankingAppGrades();

    /**
     * Model tests for BankingAppGrades
     */
    @Test
    public void testBankingAppGrades() {
        // TODO: test BankingAppGrades
    }

    /**
     * Test the property 'appleAppStore'
     */
    @Test
    public void appleAppStoreTest() {
        // TODO: test appleAppStore
    }

    /**
     * Test the property 'googlePlay'
     */
    @Test
    public void googlePlayTest() {
        // TODO: test googlePlay
    }

}
