/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.c24.giro.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CardsFees
 */
public class CardsFeesTest {
    private final CardsFees model = new CardsFees();

    /**
     * Model tests for CardsFees
     */
    @Test
    public void testCardsFees() {
        // TODO: test CardsFees
    }

    /**
     * Test the property 'giroCard'
     */
    @Test
    public void giroCardTest() {
        // TODO: test giroCard
    }

    /**
     * Test the property 'giroPartnerCard'
     */
    @Test
    public void giroPartnerCardTest() {
        // TODO: test giroPartnerCard
    }

    /**
     * Test the property 'debitCard'
     */
    @Test
    public void debitCardTest() {
        // TODO: test debitCard
    }

    /**
     * Test the property 'debitPartnerCard'
     */
    @Test
    public void debitPartnerCardTest() {
        // TODO: test debitPartnerCard
    }

    /**
     * Test the property 'creditCard'
     */
    @Test
    public void creditCardTest() {
        // TODO: test creditCard
    }

    /**
     * Test the property 'creditPartnerCard'
     */
    @Test
    public void creditPartnerCardTest() {
        // TODO: test creditPartnerCard
    }

    /**
     * Test the property 'nonEuroPayments'
     */
    @Test
    public void nonEuroPaymentsTest() {
        // TODO: test nonEuroPayments
    }

}
