/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.c24.giro.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.LinkedHashSet;
import java.util.Set;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CashWithdrawalConditions
 */
public class CashWithdrawalConditionsTest {
    private final CashWithdrawalConditions model = new CashWithdrawalConditions();

    /**
     * Model tests for CashWithdrawalConditions
     */
    @Test
    public void testCashWithdrawalConditions() {
        // TODO: test CashWithdrawalConditions
    }

    /**
     * Test the property 'enabled'
     */
    @Test
    public void enabledTest() {
        // TODO: test enabled
    }

    /**
     * Test the property 'numberOfAtms'
     */
    @Test
    public void numberOfAtmsTest() {
        // TODO: test numberOfAtms
    }

    /**
     * Test the property 'atmNetworks'
     */
    @Test
    public void atmNetworksTest() {
        // TODO: test atmNetworks
    }

    /**
     * Test the property 'withdrawalFrequency'
     */
    @Test
    public void withdrawalFrequencyTest() {
        // TODO: test withdrawalFrequency
    }

}
