/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.c24.giro.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.c24.giro.client.model.AtmWithdrawalFee;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CashFees
 */
public class CashFeesTest {
    private final CashFees model = new CashFees();

    /**
     * Model tests for CashFees
     */
    @Test
    public void testCashFees() {
        // TODO: test CashFees
    }

    /**
     * Test the property 'atmWithdrawalEuro'
     */
    @Test
    public void atmWithdrawalEuroTest() {
        // TODO: test atmWithdrawalEuro
    }

    /**
     * Test the property 'atmWithdrawalNonEuro'
     */
    @Test
    public void atmWithdrawalNonEuroTest() {
        // TODO: test atmWithdrawalNonEuro
    }

    /**
     * Test the property 'branchOrShopWithdrawal'
     */
    @Test
    public void branchOrShopWithdrawalTest() {
        // TODO: test branchOrShopWithdrawal
    }

    /**
     * Test the property 'deposit'
     */
    @Test
    public void depositTest() {
        // TODO: test deposit
    }

}
