/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.c24.giro.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Chip
 */
public class ChipTest {
    private final Chip model = new Chip();

    /**
     * Model tests for Chip
     */
    @Test
    public void testChip() {
        // TODO: test Chip
    }

    /**
     * Test the property 'enabled'
     */
    @Test
    public void enabledTest() {
        // TODO: test enabled
    }

    /**
     * Test the property 'desktopLabelText'
     */
    @Test
    public void desktopLabelTextTest() {
        // TODO: test desktopLabelText
    }

    /**
     * Test the property 'desktopHoverText'
     */
    @Test
    public void desktopHoverTextTest() {
        // TODO: test desktopHoverText
    }

    /**
     * Test the property 'desktopProductInfo'
     */
    @Test
    public void desktopProductInfoTest() {
        // TODO: test desktopProductInfo
    }

    /**
     * Test the property 'mobileLabelLongText'
     */
    @Test
    public void mobileLabelLongTextTest() {
        // TODO: test mobileLabelLongText
    }

    /**
     * Test the property 'mobileLabelShortText'
     */
    @Test
    public void mobileLabelShortTextTest() {
        // TODO: test mobileLabelShortText
    }

    /**
     * Test the property 'mobileProductInfo'
     */
    @Test
    public void mobileProductInfoTest() {
        // TODO: test mobileProductInfo
    }

}
