/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.c24.giro.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.c24.giro.client.model.AccountFees;
import de.c24.giro.client.model.CardsFees;
import de.c24.giro.client.model.CashFees;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Fees
 */
public class FeesTest {
    private final Fees model = new Fees();

    /**
     * Model tests for Fees
     */
    @Test
    public void testFees() {
        // TODO: test Fees
    }

    /**
     * Test the property 'account'
     */
    @Test
    public void accountTest() {
        // TODO: test account
    }

    /**
     * Test the property 'cards'
     */
    @Test
    public void cardsTest() {
        // TODO: test cards
    }

    /**
     * Test the property 'cash'
     */
    @Test
    public void cashTest() {
        // TODO: test cash
    }

}
