/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.c24.giro.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OpeningFees
 */
public class OpeningFeesTest {
    private final OpeningFees model = new OpeningFees();

    /**
     * Model tests for OpeningFees
     */
    @Test
    public void testOpeningFees() {
        // TODO: test OpeningFees
    }

    /**
     * Test the property 'transferAccount'
     */
    @Test
    public void transferAccountTest() {
        // TODO: test transferAccount
    }

    /**
     * Test the property 'standingOrder'
     */
    @Test
    public void standingOrderTest() {
        // TODO: test standingOrder
    }

    /**
     * Test the property 'directDebit'
     */
    @Test
    public void directDebitTest() {
        // TODO: test directDebit
    }

}
