/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.c24.giro.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.c24.giro.client.model.Bank;
import de.c24.giro.client.model.BankingAppGrades;
import de.c24.giro.client.model.Bonus;
import de.c24.giro.client.model.CashWithdrawalConditions;
import de.c24.giro.client.model.CashWithdrawalInRegion;
import de.c24.giro.client.model.Cashback;
import de.c24.giro.client.model.CreditCard;
import de.c24.giro.client.model.DebitCard;
import de.c24.giro.client.model.Doc;
import de.c24.giro.client.model.Fees;
import de.c24.giro.client.model.GiroCard;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SaveProductRequest
 */
public class SaveProductRequestTest {
    private final SaveProductRequest model = new SaveProductRequest();

    /**
     * Model tests for SaveProductRequest
     */
    @Test
    public void testSaveProductRequest() {
        // TODO: test SaveProductRequest
    }

    /**
     * Test the property 'key'
     */
    @Test
    public void keyTest() {
        // TODO: test key
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'activeSince'
     */
    @Test
    public void activeSinceTest() {
        // TODO: test activeSince
    }

    /**
     * Test the property 'activeUntil'
     */
    @Test
    public void activeUntilTest() {
        // TODO: test activeUntil
    }

    /**
     * Test the property 'bank'
     */
    @Test
    public void bankTest() {
        // TODO: test bank
    }

    /**
     * Test the property 'accountAccessWays'
     */
    @Test
    public void accountAccessWaysTest() {
        // TODO: test accountAccessWays
    }

    /**
     * Test the property 'branchesNumber'
     */
    @Test
    public void branchesNumberTest() {
        // TODO: test branchesNumber
    }

    /**
     * Test the property 'bankingAppGrades'
     */
    @Test
    public void bankingAppGradesTest() {
        // TODO: test bankingAppGrades
    }

    /**
     * Test the property 'onlineBankingSafetyProcedures'
     */
    @Test
    public void onlineBankingSafetyProceduresTest() {
        // TODO: test onlineBankingSafetyProcedures
    }

    /**
     * Test the property 'personalConsultationsServiceAvailable'
     */
    @Test
    public void personalConsultationsServiceAvailableTest() {
        // TODO: test personalConsultationsServiceAvailable
    }

    /**
     * Test the property 'specialFeatures'
     */
    @Test
    public void specialFeaturesTest() {
        // TODO: test specialFeatures
    }

    /**
     * Test the property 'giroCard'
     */
    @Test
    public void giroCardTest() {
        // TODO: test giroCard
    }

    /**
     * Test the property 'debitCard'
     */
    @Test
    public void debitCardTest() {
        // TODO: test debitCard
    }

    /**
     * Test the property 'creditCard'
     */
    @Test
    public void creditCardTest() {
        // TODO: test creditCard
    }

    /**
     * Test the property 'paymentApps'
     */
    @Test
    public void paymentAppsTest() {
        // TODO: test paymentApps
    }

    /**
     * Test the property 'giroCardCashWithdrawalConditions'
     */
    @Test
    public void giroCardCashWithdrawalConditionsTest() {
        // TODO: test giroCardCashWithdrawalConditions
    }

    /**
     * Test the property 'debitCardCashWithdrawalConditions'
     */
    @Test
    public void debitCardCashWithdrawalConditionsTest() {
        // TODO: test debitCardCashWithdrawalConditions
    }

    /**
     * Test the property 'creditCardCashWithdrawalConditions'
     */
    @Test
    public void creditCardCashWithdrawalConditionsTest() {
        // TODO: test creditCardCashWithdrawalConditions
    }

    /**
     * Test the property 'freeCashWithdrawalAbroad'
     */
    @Test
    public void freeCashWithdrawalAbroadTest() {
        // TODO: test freeCashWithdrawalAbroad
    }

    /**
     * Test the property 'cashWithdrawalByDebitCardInRegion'
     */
    @Test
    public void cashWithdrawalByDebitCardInRegionTest() {
        // TODO: test cashWithdrawalByDebitCardInRegion
    }

    /**
     * Test the property 'cashWithdrawalByCreditCardInRegion'
     */
    @Test
    public void cashWithdrawalByCreditCardInRegionTest() {
        // TODO: test cashWithdrawalByCreditCardInRegion
    }

    /**
     * Test the property 'cashWithdrawalInShop'
     */
    @Test
    public void cashWithdrawalInShopTest() {
        // TODO: test cashWithdrawalInShop
    }

    /**
     * Test the property 'cashDepositCondition'
     */
    @Test
    public void cashDepositConditionTest() {
        // TODO: test cashDepositCondition
    }

    /**
     * Test the property 'otherBankServices'
     */
    @Test
    public void otherBankServicesTest() {
        // TODO: test otherBankServices
    }

    /**
     * Test the property 'fees'
     */
    @Test
    public void feesTest() {
        // TODO: test fees
    }

    /**
     * Test the property 'bonus'
     */
    @Test
    public void bonusTest() {
        // TODO: test bonus
    }

    /**
     * Test the property 'cashback'
     */
    @Test
    public void cashbackTest() {
        // TODO: test cashback
    }

    /**
     * Test the property 'creditInterest'
     */
    @Test
    public void creditInterestTest() {
        // TODO: test creditInterest
    }

    /**
     * Test the property 'depositGuarantee'
     */
    @Test
    public void depositGuaranteeTest() {
        // TODO: test depositGuarantee
    }

    /**
     * Test the property 'sustainabilityType'
     */
    @Test
    public void sustainabilityTypeTest() {
        // TODO: test sustainabilityType
    }

    /**
     * Test the property 'docs'
     */
    @Test
    public void docsTest() {
        // TODO: test docs
    }

}
