/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.c24.giro.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.LinkedHashSet;
import java.util.Set;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SaveBankRequest
 */
public class SaveBankRequestTest {
    private final SaveBankRequest model = new SaveBankRequest();

    /**
     * Model tests for SaveBankRequest
     */
    @Test
    public void testSaveBankRequest() {
        // TODO: test SaveBankRequest
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'apiServerId'
     */
    @Test
    public void apiServerIdTest() {
        // TODO: test apiServerId
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'logoFileName'
     */
    @Test
    public void logoFileNameTest() {
        // TODO: test logoFileName
    }

    /**
     * Test the property 'blz'
     */
    @Test
    public void blzTest() {
        // TODO: test blz
    }

    /**
     * Test the property 'bic'
     */
    @Test
    public void bicTest() {
        // TODO: test bic
    }

    /**
     * Test the property 'types'
     */
    @Test
    public void typesTest() {
        // TODO: test types
    }

    /**
     * Test the property 'phone'
     */
    @Test
    public void phoneTest() {
        // TODO: test phone
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'homePage'
     */
    @Test
    public void homePageTest() {
        // TODO: test homePage
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'legalAddress'
     */
    @Test
    public void legalAddressTest() {
        // TODO: test legalAddress
    }

    /**
     * Test the property 'contactAddress'
     */
    @Test
    public void contactAddressTest() {
        // TODO: test contactAddress
    }

    /**
     * Test the property 'legalForm'
     */
    @Test
    public void legalFormTest() {
        // TODO: test legalForm
    }

    /**
     * Test the property 'yearFounded'
     */
    @Test
    public void yearFoundedTest() {
        // TODO: test yearFounded
    }

    /**
     * Test the property 'seoName'
     */
    @Test
    public void seoNameTest() {
        // TODO: test seoName
    }

    /**
     * Test the property 'activeForSeo'
     */
    @Test
    public void activeForSeoTest() {
        // TODO: test activeForSeo
    }

}
