/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.c24.giro.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import de.c24.giro.client.JSON;

/**
 * BankingAppGrades
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-08-31T13:18:43.362+02:00[Europe/Berlin]")
public class BankingAppGrades {
  public static final String SERIALIZED_NAME_APPLE_APP_STORE = "appleAppStore";
  @SerializedName(SERIALIZED_NAME_APPLE_APP_STORE)
  private Double appleAppStore;

  public static final String SERIALIZED_NAME_GOOGLE_PLAY = "googlePlay";
  @SerializedName(SERIALIZED_NAME_GOOGLE_PLAY)
  private Double googlePlay;

  public BankingAppGrades() {
  }

  public BankingAppGrades appleAppStore(Double appleAppStore) {
    
    this.appleAppStore = appleAppStore;
    return this;
  }

   /**
   * Get appleAppStore
   * @return appleAppStore
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Double getAppleAppStore() {
    return appleAppStore;
  }


  public void setAppleAppStore(Double appleAppStore) {
    this.appleAppStore = appleAppStore;
  }


  public BankingAppGrades googlePlay(Double googlePlay) {
    
    this.googlePlay = googlePlay;
    return this;
  }

   /**
   * Get googlePlay
   * @return googlePlay
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Double getGooglePlay() {
    return googlePlay;
  }


  public void setGooglePlay(Double googlePlay) {
    this.googlePlay = googlePlay;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BankingAppGrades bankingAppGrades = (BankingAppGrades) o;
    return Objects.equals(this.appleAppStore, bankingAppGrades.appleAppStore) &&
        Objects.equals(this.googlePlay, bankingAppGrades.googlePlay);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appleAppStore, googlePlay);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BankingAppGrades {\n");
    sb.append("    appleAppStore: ").append(toIndentedString(appleAppStore)).append("\n");
    sb.append("    googlePlay: ").append(toIndentedString(googlePlay)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("appleAppStore");
    openapiFields.add("googlePlay");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to BankingAppGrades
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (BankingAppGrades.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in BankingAppGrades is not found in the empty JSON string", BankingAppGrades.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!BankingAppGrades.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `BankingAppGrades` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BankingAppGrades.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BankingAppGrades' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BankingAppGrades> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BankingAppGrades.class));

       return (TypeAdapter<T>) new TypeAdapter<BankingAppGrades>() {
           @Override
           public void write(JsonWriter out, BankingAppGrades value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BankingAppGrades read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of BankingAppGrades given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of BankingAppGrades
  * @throws IOException if the JSON string is invalid with respect to BankingAppGrades
  */
  public static BankingAppGrades fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BankingAppGrades.class);
  }

 /**
  * Convert an instance of BankingAppGrades to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

