/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.c24.giro.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import de.c24.giro.client.JSON;

/**
 * GraduatedMaintenanceFeeEntry
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-08-31T13:18:43.362+02:00[Europe/Berlin]")
public class GraduatedMaintenanceFeeEntry {
  public static final String SERIALIZED_NAME_FROM_MONTHLY_DEPOSIT = "fromMonthlyDeposit";
  @SerializedName(SERIALIZED_NAME_FROM_MONTHLY_DEPOSIT)
  private Float fromMonthlyDeposit;

  public static final String SERIALIZED_NAME_TO_MONTHLY_DEPOSIT = "toMonthlyDeposit";
  @SerializedName(SERIALIZED_NAME_TO_MONTHLY_DEPOSIT)
  private Float toMonthlyDeposit;

  public static final String SERIALIZED_NAME_FEE = "fee";
  @SerializedName(SERIALIZED_NAME_FEE)
  private Float fee;

  public GraduatedMaintenanceFeeEntry() {
  }

  public GraduatedMaintenanceFeeEntry fromMonthlyDeposit(Float fromMonthlyDeposit) {
    
    this.fromMonthlyDeposit = fromMonthlyDeposit;
    return this;
  }

   /**
   * Get fromMonthlyDeposit
   * @return fromMonthlyDeposit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Float getFromMonthlyDeposit() {
    return fromMonthlyDeposit;
  }


  public void setFromMonthlyDeposit(Float fromMonthlyDeposit) {
    this.fromMonthlyDeposit = fromMonthlyDeposit;
  }


  public GraduatedMaintenanceFeeEntry toMonthlyDeposit(Float toMonthlyDeposit) {
    
    this.toMonthlyDeposit = toMonthlyDeposit;
    return this;
  }

   /**
   * Get toMonthlyDeposit
   * @return toMonthlyDeposit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Float getToMonthlyDeposit() {
    return toMonthlyDeposit;
  }


  public void setToMonthlyDeposit(Float toMonthlyDeposit) {
    this.toMonthlyDeposit = toMonthlyDeposit;
  }


  public GraduatedMaintenanceFeeEntry fee(Float fee) {
    
    this.fee = fee;
    return this;
  }

   /**
   * Get fee
   * @return fee
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Float getFee() {
    return fee;
  }


  public void setFee(Float fee) {
    this.fee = fee;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GraduatedMaintenanceFeeEntry graduatedMaintenanceFeeEntry = (GraduatedMaintenanceFeeEntry) o;
    return Objects.equals(this.fromMonthlyDeposit, graduatedMaintenanceFeeEntry.fromMonthlyDeposit) &&
        Objects.equals(this.toMonthlyDeposit, graduatedMaintenanceFeeEntry.toMonthlyDeposit) &&
        Objects.equals(this.fee, graduatedMaintenanceFeeEntry.fee);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fromMonthlyDeposit, toMonthlyDeposit, fee);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GraduatedMaintenanceFeeEntry {\n");
    sb.append("    fromMonthlyDeposit: ").append(toIndentedString(fromMonthlyDeposit)).append("\n");
    sb.append("    toMonthlyDeposit: ").append(toIndentedString(toMonthlyDeposit)).append("\n");
    sb.append("    fee: ").append(toIndentedString(fee)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("fromMonthlyDeposit");
    openapiFields.add("toMonthlyDeposit");
    openapiFields.add("fee");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to GraduatedMaintenanceFeeEntry
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (GraduatedMaintenanceFeeEntry.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in GraduatedMaintenanceFeeEntry is not found in the empty JSON string", GraduatedMaintenanceFeeEntry.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!GraduatedMaintenanceFeeEntry.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GraduatedMaintenanceFeeEntry` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GraduatedMaintenanceFeeEntry.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GraduatedMaintenanceFeeEntry' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GraduatedMaintenanceFeeEntry> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GraduatedMaintenanceFeeEntry.class));

       return (TypeAdapter<T>) new TypeAdapter<GraduatedMaintenanceFeeEntry>() {
           @Override
           public void write(JsonWriter out, GraduatedMaintenanceFeeEntry value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GraduatedMaintenanceFeeEntry read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of GraduatedMaintenanceFeeEntry given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of GraduatedMaintenanceFeeEntry
  * @throws IOException if the JSON string is invalid with respect to GraduatedMaintenanceFeeEntry
  */
  public static GraduatedMaintenanceFeeEntry fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GraduatedMaintenanceFeeEntry.class);
  }

 /**
  * Convert an instance of GraduatedMaintenanceFeeEntry to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

